/**
 * NEOLAF Vibe Coding Bootcamp — Weeks 4-5 Agent Starter
 *
 * IMPORTANT: Do not edit this file manually.
 * Direct your AI agent to customize it.
 *
 * Starter prompt for Week 4, Day 1:
 * "I have a basic Cloudflare Agent starter. Please help me implement:
 *  1. KSTAR memory using Durable Objects (K=knowledge, S=situation, T=task, A=action, R=result)
 *  2. A method to store and retrieve episodic memories
 *  3. A method to demonstrate that the agent learns from previous interactions
 *  4. Proper TypeScript types for all KSTAR components"
 */

import { Agent, AgentContext } from "@cloudflare/agents";

// KSTAR Memory Types
// Customize these with your AI agent
interface KSTARMemory {
  knowledge: KnowledgeEntry[];
  situation: SituationEntry;
  tasks: TaskEntry[];
  actions: ActionEntry[];
  results: ResultEntry[];
}

interface KnowledgeEntry {
  id: string;
  content: string;
  timestamp: number;
  tags: string[];
}

interface SituationEntry {
  currentContext: string;
  userProfile: Record<string, unknown>;
  lastUpdated: number;
}

interface TaskEntry {
  id: string;
  description: string;
  status: "pending" | "in_progress" | "completed" | "failed";
  createdAt: number;
}

interface ActionEntry {
  id: string;
  taskId: string;
  action: string;
  result: string;
  timestamp: number;
}

interface ResultEntry {
  id: string;
  actionId: string;
  evaluation: string;
  lesson: string;
  timestamp: number;
}

// Starter Agent Class
// Direct your AI agent to extend this with full KSTAR memory implementation
export class VibeCodingAgent extends Agent<Env> {
  
  async onMessage(message: string, context: AgentContext): Promise<string> {
    // TODO: Direct your AI agent to implement:
    // 1. Retrieve relevant KSTAR memories
    // 2. Build context from memories
    // 3. Generate response using LLM
    // 4. Store new memories
    // 5. Return response
    
    return `Agent received: ${message}. Direct your AI agent to implement the full KSTAR memory loop here.`;
  }

  async storeMemory(entry: KnowledgeEntry): Promise<void> {
    // TODO: Direct your AI agent to implement Durable Objects storage
    console.log("Storing memory:", entry);
  }

  async retrieveMemories(query: string): Promise<KnowledgeEntry[]> {
    // TODO: Direct your AI agent to implement semantic memory retrieval
    return [];
  }
}

// Cloudflare Workers environment bindings
// Direct your AI agent to add your specific bindings here
interface Env {
  // Example bindings - customize with your AI agent:
  // AGENT_MEMORY: DurableObjectNamespace;
  // AI: Ai;
  // KV: KVNamespace;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // TODO: Direct your AI agent to implement the full request handler
    return new Response("NEOLAF Vibe Coding Agent - Week 4 Starter. Direct your AI agent to implement the full handler.", {
      headers: { "Content-Type": "text/plain" }
    });
  }
};
